### PR TITLE
No stack trace for production

### PR DESCRIPTION
**Pull request by zxan1285**
✏️ Changes
We don't want to show stack trace to the users. Especially on production.
These changes are hiding stack trace for production environment.

🔗 References
Jira: https://auth0team.atlassian.net/projects/KEY/issues/KEY-127

🎯 Testing
✅ This has been tested locally
✅ This has been tested in a webtask

### CODE REVIEW

**Comment by auth0extensions** [comment]
MD5: ca9c491ac66b2c62500882e93f3719a8

# NSP - Security Report

_This is an automated security audit of this project. Please do not modify its contents_

Vulnerabilities found: **5**
Affected Modules: **hoek, hoek, superagent, superagent, mime**
Summary:

- Prototype pollution attack
- Prototype pollution attack
- Large gzip Denial of Service
- Large gzip Denial of Service
- Regular Expression Denial of Service


## Detailed report
#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-extension-tools@1.3.1 > jsonwebtoken@7.4.3 > joi@6.10.1 > hoek@2.16.3**

---

#### Prototype pollution attack

Affected Module: **hoek**
Installed version: **2.16.3**
Patched versions: **> 4.2.0 < 5.0.0 || >= 5.0.3**
Advisory: https://nodesecurity.io/advisories/566
Path: **auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > boom@2.10.1 > hoek@2.16.3**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **2.3.0**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-extension-tools@1.3.1 > superagent@2.3.0**

---

#### Large gzip Denial of Service

Affected Module: **superagent**
Installed version: **1.8.5**
Patched versions: **>=3.7.0**
Advisory: https://nodesecurity.io/advisories/479
Path: **auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5**

---

#### Regular Expression Denial of Service

Affected Module: **mime**
Installed version: **1.3.4**
Patched versions: **>= 1.4.1 < 2.0.0 || >= 2.0.3**
Advisory: https://nodesecurity.io/advisories/535
Path: **auth0-extension-tools@1.3.1 > webtask-tools@2.2.0 > superagent@1.8.5 > mime@1.3.4**

---

**Comment by fyockm** [comment]
@zxan1285 changes LGTM

could we also update some of the modules listed above and retest?
- `jsonwebtoken@8.3.0`
- `webtask-tools@3.2.0`

**Comment by fyockm** [comment]
@zxan1285 tests are now failing for me. do they pass for you?

**Comment by fyockm** [comment]
`auth0-extension-tools@1.3.2` published to npm

**Pull request merged**
